#define ALGORITHM        1
#define ENDAALGORITHM    2
#define INPUT            3
#define OUTPUT           4
#define IF               5
#define THEN             6
#define ELSE             7
#define ELSEIF           8
#define ENDIF            9
#define WHILE            10
#define DO               11
#define ENDWHILE         12
#define FOR              13
#define TO               14
#define ENDFOR           15
#define REPEAT           16
#define UNTIL            17
#define SWITCH           18
#define CASE             19
#define DEFAULT          20
#define ENDSWITCH        21
#define BREAK            22
#define CONTINUE         23
#define PROCEDURE        24
#define ENDPROCEDURE     25
#define RETURN           26
#define VOID             27
#define MAIN             28
#define PRINT            29
#define SCAN             30
#define PLUS             31
#define MINUS            32
#define MULT             33
#define DIV              34
#define ASSIGN           35
#define EQUAL            36
#define NOTEQUAL         37
#define LESS             38
#define GREATER          39
#define LESSEQUAL        40
#define GREATEREQUAL     41
#define AND              42
#define OR               43
#define NOT              44
#define LPAREN           45
#define RPAREN           46
#define SEMICOLON        47
#define COMMA            48
#define INTEGER          49
#define FLOAT            50
#define STRING           51
#define BOOLEAN          52
#define IDENTIFIER       53

